[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/go"
  to = "/.netlify/functions/go"
  status = 200

[[redirects]]
  from = "/links"
  to = "/.netlify/functions/links"
  status = 200
